# Generated by Django 4.1.3 on 2022-12-17 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('spritual_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('date_of_arrival', models.CharField(default='23-OCT', max_length=10)),
                ('time_of_help', models.CharField(default='00:00', max_length=10)),
                ('duration_of_help', models.CharField(default='DAY:1', max_length=5)),
                ('help_on_departure', models.CharField(default='00:00', max_length=10)),
                ('special_skill', models.CharField(max_length=200)),
                ('previous_volunteering_department', models.CharField(max_length=200)),
                ('hour_of_help', models.IntegerField(default=0)),
                ('primary_manager', models.BooleanField(default=False)),
                ('area_of_management', models.CharField(max_length=200)),
                ('register_for_seva', models.CharField(max_length=200)),
                ('type_of_seva', models.CharField(max_length=200)),
                ('seva_preference', models.CharField(max_length=200)),
                ('age', models.CharField(default=0, max_length=10)),
                ('sleep_dormitory', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('privacy_policy', models.BooleanField(default=False)),
                ('suscribe_to_newsletter', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
