# Generated by Django 4.1.3 on 2022-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_form',
            name='area_of_management',
            field=models.CharField(choices=[('BKO Disposal', 'BKO Disposal'), ('BKO Hygiene(deputy)', 'BKO Hygiene(deputy)'), ('HV Hygiene- dismantling', 'HV Hygiene- dismantaling'), ('HV Disposal - Building inside', 'HV Disposal - Building inside'), ('HV Disposal - kitchen and kompost', 'HV Disposal - kitchen and kompost'), ('HV Seva', 'HV Seva'), ('HV vegetable cutting', 'HV vegetable cutting'), ('HV Staff', 'HV Staff'), ('HV Sanitation', 'HV Sanitation'), ('HV security', 'HV security'), ('HV Flower', 'HV Flower'), ('HV Seva comunication', 'HV Seva comunication'), ('HV Storage room', 'HV Storage room')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='date_of_arrival',
            field=models.CharField(choices=[('23-OCT', '23-OCT'), ('24-OCT', '24-OCT'), ('25-OCT', '25-OCT'), ('26-OCT', '26-OCT'), ('27-OCT', '27-OCT')], default='23-OCT', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='duration_of_help',
            field=models.CharField(choices=[('DAY:1', 'DAY:1'), ('DAY:2', 'DAY:2'), ('DAY:3', 'DAY:3'), ('DAY:4', 'DAY:4'), ('DAY:5', 'DAY:5')], default='DAY:1', max_length=5),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='help_on_departure',
            field=models.CharField(choices=[('00:00', '00:00'), ('00:30', '00:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00'), ('05:30', '05:30'), ('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='register_for_seva',
            field=models.CharField(choices=[("Option 1: I'm not registered yet", "Option 1: I'm not registered yet"), ("option 2: I'm registered for seva", "option 2: I'm registered for seva"), ("option 3: I'm registered for seva and I'm a manager", "option 3: I'm registered for seva and I'm a manager")], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='seva_preference',
            field=models.CharField(choices=[('Hygine and cleaning', 'Hygine and cleaning'), ('Waste Disposal', 'Waste Disposal'), ('Wadrobe', 'Warobe'), ('Setup and dismantling', 'Setup and dismantling'), ('Parking', 'Parking'), ('Web developer', 'Web developer')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='time_of_help',
            field=models.CharField(choices=[('00:00', '00:00'), ('00:30', '00:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00'), ('05:30', '05:30'), ('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30'), ('23:00', '23:00'), ('23:30', '23:30'), ('24:00', '24:00')], default='00:00', max_length=10),
        ),
    ]
