# Generated by Django 4.1.4 on 2022-12-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_form_area_of_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_form',
            name='age',
            field=models.CharField(choices=[('< 18', '< 18'), ('18-30', '18-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('above 60', 'above 70')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='area_of_management',
            field=models.CharField(blank=True, choices=[('BKO Disposal', 'BKO Disposal'), ('BKO Hygiene(deputy)', 'BKO Hygiene(deputy)'), ('HV Hygiene- dismantling', 'HV Hygiene- dismantaling'), ('HV Disposal - Building inside', 'HV Disposal - Building inside'), ('HV Disposal - kitchen and kompost', 'HV Disposal - kitchen and kompost'), ('HV Seva', 'HV Seva'), ('HV vegetable cutting', 'HV vegetable cutting'), ('HV Staff', 'HV Staff'), ('HV Sanitation', 'HV Sanitation'), ('HV security', 'HV security'), ('HV Flower', 'HV Flower'), ('HV Seva comunication', 'HV Seva comunication'), ('HV Storage room', 'HV Storage room')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='previous_volunteering_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='seva_preference',
            field=models.CharField(blank=True, choices=[('Hygine and cleaning', 'Hygine and cleaning'), ('Waste Disposal', 'Waste Disposal'), ('Wadrobe', 'Warobe'), ('Setup and dismantling', 'Setup and dismantling'), ('Parking', 'Parking'), ('Web developer', 'Web developer')], max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='special_skill',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='spritual_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user_form',
            name='suscribe_to_newsletter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
